name: GitHub Actions to Dockerhub
run-name: ${{ github.actor }} Run GitHub Actions to upload docker image 🚀
on: [push]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: build and tag image
      run: |
        docker build -t subagio99/uas-pccks:latest -f Dockerfile .

    
    - name: push to dockerhub
      run: docker login -u ${{UAS_PCCKS_2022.[subagio99]}} -p ${{UAS_PCCKS_2022.[dckr_pat_aSb1zqLI3Bqw5ufLF0yj1fBGU0c]}} && docker push subagio99/uas-pccks:latest
