name: GitHub Actions to Dockerhub
run-name: ${{ github.actor }} Run GitHub Actions to upload docker image 🚀
on: [push]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: build and tag image
      run: |
        docker build -t subagio99/uas-pccks:latest -f Dockerfile .

    
    - name: push to dockerhub
      run: docker login -u ${{secrets.subagio99}} -p ${{secrets.dckr_pat_ZnWfBtfRogYJDl5JfuWYM1nGfXU}} && docker push subagio99/uas-pccks:latest